### PR TITLE
Migrating to ocaml-planet.

### PR DESCRIPTION
**Pull request by kayceesrk**
Uses ocaml-planet for feed aggregation. URL fetching is more robust; handles unavailable links.

### CODE REVIEW

**Comment by avsm** [comment]
Conflicts :( I've just been editing this part of the site.

**Comment by kayceesrk** [comment]
Not a problem. Let me know once you are done with edits. I can merge the changes.

**Comment by avsm** [comment]
I've just pushed my last changes, so should be good if you could rebase yours.

**Comment by kayceesrk** [comment]
Great! Will do it now.

**Comment by kayceesrk** [comment]
Merged the latest edits.

**Comment by kayceesrk** [comment]
Added Quelea paper and atom feed for blogs. Included more feeds in blogs.

**Comment by avsm** [comment]
Hm, @amirmc's is failing with:

```
Downloading http://amirchaudhry.com/tags/ocaml-labs-atom.xml ... Failed: resolution failed: no scheme
```

**Comment by kayceesrk** [comment]
ocaml-planet-0.1.1 fixes it. Upgrade to the latest version. 

BTW How do I specify a particular version of a package with ocamlbuild (used by ocl-reporter Makefile)?

**Comment by amirmc** [comment]
That reminds me.  I need to replace that URL with the following (I have two and should consolidate).  I'll commit it directly as long as I'm not about to clash with anything.

http://amirchaudhry.com/tags/ocamllabs-atom.xml  (just one less hyphen)

**Comment by amirmc** [comment]
> I'll commit it directly as long as I'm not about to clash with anything.

Just FYI, this is done.

**Pull request merged**
